# Generated by Django 3.0.8 on 2020-08-03 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DailyPrediction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('attendance_pred', models.TextField()),
                ('food_pred', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='DailyTrue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('attendance_true', models.TextField()),
                ('food_true', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField()),
                ('api_key', models.TextField()),
                ('net_id', models.TextField()),
                ('mv_serial', models.TextField()),
                ('server_ip', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('acc', models.TextField()),
                ('is_discrepancy', models.TextField()),
                ('pred', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.DailyPrediction')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.School')),
                ('true', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.DailyTrue')),
            ],
        ),
        migrations.CreateModel(
            name='Discrepancy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.TextField()),
                ('assign_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Admin')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Reports')),
            ],
        ),
        migrations.AddField(
            model_name='dailytrue',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.School'),
        ),
        migrations.AddField(
            model_name='dailyprediction',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.School'),
        ),
    ]
