# Generated by Django 3.0.8 on 2020-08-03 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyprediction',
            name='food_pred',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dailytrue',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='dailytrue',
            name='food_true',
            field=models.TextField(),
        ),
    ]
